name: flutter_tdd_clean_arch_solid_desin_patterns
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  faker: ^1.3.0
  flutter:
    sdk: flutter
  mockito: ^3.0.2
  get: ^3.4.2
  test: ^1.15.0
  http: 
  provider: ^4.3.2+3
  flutter_secure_storage: ^3.3.3
  carousel_slider: ^2.3.1
  card_swiper: ^2.0.4
  equatable: ^1.2.5
  intl: ^0.16.1


dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  image_test_utils:

flutter:

  uses-material-design: true
  assets:
    - lib/ui/assets/
